### ISSUE TITLE
Development status of this repo

### ISSUE THREAD

**Issue by elichad** [beerphilipp/ro-crates-deposit#2]
Hi @beerphilipp and @milanszente, I'm interested in using (and further developing) this project for Zenodo uploads of RO-Crates, now that Zenodo uses InvenioRDM (I have been working on my own similar project https://github.com/ResearchObject/ro-crate-uploader before discovering this one but haven't got as far). 

I see there haven't been any commits in a while - are either of you still available to maintain the repo, discuss development, review PRs, etc?

Thanks :) 

Edit for context: I'm part of the RO-Crate team at the University of Manchester, UK, with a focus on RO-Crate tooling.

**Comment by beerphilipp** [comment]
Hi @elichad,

I'm glad to hear that this repository is of use to someone! This project started as a university assignment, and we are not actively maintaining it anymore. However, we welcome you to further develop it. :)

Please note that the project is not fully tested, so there may be some bugs that need fixing. If you have any questions or need any information about the original implementation, feel free to reach out.

Best of luck with your development :)

Best,
Philipp

**Comment by elichad** [comment]
Thanks @beerphilipp for the information! I've made a fork over in https://github.com/ResearchObject/ro-crates-deposit and will do some further development there.
